# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/shold/Desktop/EIE-Y2/ghost_new_ip/ghost_game/ghost_game.srcs/sources_1/bd/ghost_bd/ip/ghost_bd_gpio_ghost3_0/ghost_bd_gpio_ghost3_0.xci
# IP: The module: 'ghost_bd_gpio_ghost3_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/shold/Desktop/EIE-Y2/ghost_new_ip/ghost_game/ghost_game.gen/sources_1/bd/ghost_bd/ip/ghost_bd_gpio_ghost3_0/ghost_bd_gpio_ghost3_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ghost_bd_gpio_ghost3_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/shold/Desktop/EIE-Y2/ghost_new_ip/ghost_game/ghost_game.gen/sources_1/bd/ghost_bd/ip/ghost_bd_gpio_ghost3_0/ghost_bd_gpio_ghost3_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ghost_bd_gpio_ghost3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/shold/Desktop/EIE-Y2/ghost_new_ip/ghost_game/ghost_game.gen/sources_1/bd/ghost_bd/ip/ghost_bd_gpio_ghost3_0/ghost_bd_gpio_ghost3_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ghost_bd_gpio_ghost3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/shold/Desktop/EIE-Y2/ghost_new_ip/ghost_game/ghost_game.srcs/sources_1/bd/ghost_bd/ip/ghost_bd_gpio_ghost3_0/ghost_bd_gpio_ghost3_0.xci
# IP: The module: 'ghost_bd_gpio_ghost3_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/shold/Desktop/EIE-Y2/ghost_new_ip/ghost_game/ghost_game.gen/sources_1/bd/ghost_bd/ip/ghost_bd_gpio_ghost3_0/ghost_bd_gpio_ghost3_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ghost_bd_gpio_ghost3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/shold/Desktop/EIE-Y2/ghost_new_ip/ghost_game/ghost_game.gen/sources_1/bd/ghost_bd/ip/ghost_bd_gpio_ghost3_0/ghost_bd_gpio_ghost3_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ghost_bd_gpio_ghost3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/shold/Desktop/EIE-Y2/ghost_new_ip/ghost_game/ghost_game.gen/sources_1/bd/ghost_bd/ip/ghost_bd_gpio_ghost3_0/ghost_bd_gpio_ghost3_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ghost_bd_gpio_ghost3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
