# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ghost_bd/ghost_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ghost_bd || ORIG_REF_NAME==ghost_bd} -quiet] -quiet

# IP: bd/ghost_bd/ip/ghost_bd_processing_system7_0_0/ghost_bd_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ghost_bd_processing_system7_0_0 || ORIG_REF_NAME==ghost_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/ghost_bd/ip/ghost_bd_proc_sys_reset_0_0/ghost_bd_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ghost_bd_proc_sys_reset_0_0 || ORIG_REF_NAME==ghost_bd_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/ghost_bd/ip/ghost_bd_smartconnect_0_0/ghost_bd_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ghost_bd_smartconnect_0_0 || ORIG_REF_NAME==ghost_bd_smartconnect_0_0} -quiet] -quiet

# IP: bd/ghost_bd/ip/ghost_bd_ghost_multi_0_0/ghost_bd_ghost_multi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ghost_bd_ghost_multi_0_0 || ORIG_REF_NAME==ghost_bd_ghost_multi_0_0} -quiet] -quiet

# IP: bd/ghost_bd/ip/ghost_bd_gpio_ghost1_0/ghost_bd_gpio_ghost1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ghost_bd_gpio_ghost1_0 || ORIG_REF_NAME==ghost_bd_gpio_ghost1_0} -quiet] -quiet

# IP: bd/ghost_bd/ip/ghost_bd_gpio_ghost2_0/ghost_bd_gpio_ghost2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ghost_bd_gpio_ghost2_0 || ORIG_REF_NAME==ghost_bd_gpio_ghost2_0} -quiet] -quiet

# IP: bd/ghost_bd/ip/ghost_bd_gpio_ghost3_0/ghost_bd_gpio_ghost3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ghost_bd_gpio_ghost3_0 || ORIG_REF_NAME==ghost_bd_gpio_ghost3_0} -quiet] -quiet

# IP: bd/ghost_bd/ip/ghost_bd_gpio_ghost4_0/ghost_bd_gpio_ghost4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ghost_bd_gpio_ghost4_0 || ORIG_REF_NAME==ghost_bd_gpio_ghost4_0} -quiet] -quiet

# IP: bd/ghost_bd/ip/ghost_bd_gpio_rover_0/ghost_bd_gpio_rover_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ghost_bd_gpio_rover_0 || ORIG_REF_NAME==ghost_bd_gpio_rover_0} -quiet] -quiet

# IP: bd/ghost_bd/ip/ghost_bd_slice_ghost1_row_0/ghost_bd_slice_ghost1_row_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ghost_bd_slice_ghost1_row_0 || ORIG_REF_NAME==ghost_bd_slice_ghost1_row_0} -quiet] -quiet

# IP: bd/ghost_bd/ip/ghost_bd_slice_ghost1_col_0/ghost_bd_slice_ghost1_col_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ghost_bd_slice_ghost1_col_0 || ORIG_REF_NAME==ghost_bd_slice_ghost1_col_0} -quiet] -quiet

# IP: bd/ghost_bd/ip/ghost_bd_slice_ghost2_row_0/ghost_bd_slice_ghost2_row_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ghost_bd_slice_ghost2_row_0 || ORIG_REF_NAME==ghost_bd_slice_ghost2_row_0} -quiet] -quiet

# IP: bd/ghost_bd/ip/ghost_bd_slice_ghost2_col_0/ghost_bd_slice_ghost2_col_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ghost_bd_slice_ghost2_col_0 || ORIG_REF_NAME==ghost_bd_slice_ghost2_col_0} -quiet] -quiet

# IP: bd/ghost_bd/ip/ghost_bd_slice_ghost3_row_0/ghost_bd_slice_ghost3_row_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ghost_bd_slice_ghost3_row_0 || ORIG_REF_NAME==ghost_bd_slice_ghost3_row_0} -quiet] -quiet

# IP: bd/ghost_bd/ip/ghost_bd_slice_ghost3_col_0/ghost_bd_slice_ghost3_col_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ghost_bd_slice_ghost3_col_0 || ORIG_REF_NAME==ghost_bd_slice_ghost3_col_0} -quiet] -quiet

# IP: bd/ghost_bd/ip/ghost_bd_slice_ghost4_row_0/ghost_bd_slice_ghost4_row_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ghost_bd_slice_ghost4_row_0 || ORIG_REF_NAME==ghost_bd_slice_ghost4_row_0} -quiet] -quiet

# IP: bd/ghost_bd/ip/ghost_bd_slice_ghost4_col_0/ghost_bd_slice_ghost4_col_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ghost_bd_slice_ghost4_col_0 || ORIG_REF_NAME==ghost_bd_slice_ghost4_col_0} -quiet] -quiet

# IP: bd/ghost_bd/ip/ghost_bd_slice_rover_row_0/ghost_bd_slice_rover_row_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ghost_bd_slice_rover_row_0 || ORIG_REF_NAME==ghost_bd_slice_rover_row_0} -quiet] -quiet

# IP: bd/ghost_bd/ip/ghost_bd_slice_rover_col_0/ghost_bd_slice_rover_col_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ghost_bd_slice_rover_col_0 || ORIG_REF_NAME==ghost_bd_slice_rover_col_0} -quiet] -quiet

# XDC: c:/Users/shold/Desktop/EIE-Y2/ghost_new_ip/ghost_game/ghost_game.gen/sources_1/bd/ghost_bd/ghost_bd_ooc.xdc
